# Generated by Django 3.2.8 on 2022-05-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackUp_PDFS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField()),
                ('pdf', models.TextField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='backup_payroll',
            name='payroll_document',
            field=models.TextField(default='', unique=True),
        ),
    ]
