# Generated by Django 3.2.8 on 2022-05-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220520_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup_payroll',
            name='payroll_document',
            field=models.TextField(default=''),
        ),
    ]
