# Generated by Django 3.2.8 on 2022-05-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220527_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup_pdfs',
            name='pk_company',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='backup_pdfs',
            name='pk_invoice',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='backup_pdfs',
            name='token',
            field=models.CharField(default='', max_length=96),
        ),
    ]
